//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PageSession from "@/components/PageSession";
import { EntityConfig } from "@/utils/config/EntityConfig";
import EntityStateHolder from "@/components/entities/EntityStateHolder";

const config = EntityConfig;

export const metadata = {
  title: config.pluralizedVerboseModelName,
};

const Entities: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full mx-auto text-sm 2xl:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 pl-4 mx-auto rounded-sm">
          <EntityStateHolder modelConfig={config} />
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default Entities;
