//Generated by WriteToLayout_tsx - GenerateMainLayoutSidebar
import Footer from "@/components/Footer";
import SessionButton from "@/components/header/SessionButton";
import DarkLightToggle from "@/components/header/DarkLightToggle";
import { GlobalDialog } from "@/components/GlobalDialog";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <main className="flex flex-col flex-1 gap-4 pt-4 pl-0 pr-4">
        <div className="flex self-end gap-4">
          <SessionButton />
          <DarkLightToggle />
        </div>
        {children}
        <GlobalDialog />
        <Footer />
      </main>
    </>
  );
}
