//Generated by WriteToAppconfig_ts - AppConfig.ts
import { ModelConfig } from "@/interfaces/ModelConfig";
//Generated by GetAllModelConfigImports
import { EntityCategoryConfig } from "@/utils/config/EntityCategoryConfig";//Generated by GetModelConfigImports - GetModelConfigImports
import { ContactCategoryConfig } from "@/utils/config/ContactCategoryConfig";//Generated by GetModelConfigImports - GetModelConfigImports
import { BuyerStatusConfig } from "@/utils/config/BuyerStatusConfig";//Generated by GetModelConfigImports - GetModelConfigImports
import { EntityConfig } from "@/utils/config/EntityConfig";//Generated by GetModelConfigImports - GetModelConfigImports
import { PropertyConfig } from "@/utils/config/PropertyConfig";//Generated by GetModelConfigImports - GetModelConfigImports
import { PropertyStatusConfig } from "@/utils/config/PropertyStatusConfig";//Generated by GetModelConfigImports - GetModelConfigImports


interface RelationshipInterface {
    seqModelRelationshipID: number;
backendProjectID: number;
leftModelID: number;
rightModelID: number;
relationship: string;
leftForeignKey: string;
rightForeignKey: string;
declareInModel: number | null;
through: number | null;
isSimpleRelationship: boolean;
fieldToBeInserted: string | null;
excludeInForm: boolean;
listName: string | null;
excludeInRequiredList: boolean;
includeAsDropzone: boolean;
asListOnly: boolean;
excludeInTable: boolean;
includeAsLocalDropzone: boolean;
leftModelName: string;
leftPluralizedModelName: string;
rightModelName: string;
}

interface AppConfigType {
    appName: string;
sidebarEnabled: boolean;
appTitle: string;
limit: number;
sanitizedAppName: string;
    models: ModelConfig[],
    relationships: RelationshipInterface[]
}

export const AppConfig: AppConfigType = {
    appName: "panda-realty",
sidebarEnabled: true,
appTitle: "Panda Realty CRM",
limit: 10,
sanitizedAppName: "panda_realty",
    models: [//Generated by GetAllSeqModelKeys
EntityCategoryConfig,
ContactCategoryConfig,
BuyerStatusConfig,
EntityConfig,
PropertyConfig,
PropertyStatusConfig,],
    relationships: [//Generated by GetAllSeqModelRelationshipKeys
{
seqModelRelationshipID: 143,
backendProjectID: 10,
leftModelID: 99,
rightModelID: 97,
relationship: "1:M",
leftForeignKey: "contact_category_id",
rightForeignKey: "id",
declareInModel: null,
through: null,
isSimpleRelationship: false,
fieldToBeInserted: null,
excludeInForm: false,
listName: null,
excludeInRequiredList: false,
includeAsDropzone: false,
asListOnly: false,
excludeInTable: false,
includeAsLocalDropzone: false,
leftModelName: "Entity",
leftPluralizedModelName: "Entities",
rightModelName: "ContactCategory",
},
{
seqModelRelationshipID: 144,
backendProjectID: 10,
leftModelID: 99,
rightModelID: 95,
relationship: "1:M",
leftForeignKey: "entity_category_id",
rightForeignKey: "id",
declareInModel: null,
through: null,
isSimpleRelationship: false,
fieldToBeInserted: null,
excludeInForm: false,
listName: null,
excludeInRequiredList: false,
includeAsDropzone: false,
asListOnly: false,
excludeInTable: false,
includeAsLocalDropzone: false,
leftModelName: "Entity",
leftPluralizedModelName: "Entities",
rightModelName: "EntityCategory",
},
{
seqModelRelationshipID: 145,
backendProjectID: 10,
leftModelID: 99,
rightModelID: 98,
relationship: "1:M",
leftForeignKey: "buyer_status_id",
rightForeignKey: "id",
declareInModel: null,
through: null,
isSimpleRelationship: false,
fieldToBeInserted: null,
excludeInForm: false,
listName: null,
excludeInRequiredList: false,
includeAsDropzone: false,
asListOnly: false,
excludeInTable: false,
includeAsLocalDropzone: false,
leftModelName: "Entity",
leftPluralizedModelName: "Entities",
rightModelName: "BuyerStatus",
},],
}
