//Generated by WriteToGetmodeloptions_tsx - getModelOptions.tsx
//Generated by GetAllComponentImport
//Generated by GetComponentImport - GetComponentImport
import EntityCategoryForm from "@/components/entity-categories/EntityCategoryForm";
import EntityCategorySingleColumn from "@/components/entity-categories/EntityCategorySingleColumn";
//Generated by GetComponentImport - GetComponentImport
import ContactCategoryForm from "@/components/contact-categories/ContactCategoryForm";
import ContactCategorySingleColumn from "@/components/contact-categories/ContactCategorySingleColumn";
//Generated by GetComponentImport - GetComponentImport
import BuyerStatusForm from "@/components/buyer-status/BuyerStatusForm";
import BuyerStatusSingleColumn from "@/components/buyer-status/BuyerStatusSingleColumn";
//Generated by GetComponentImport - GetComponentImport
import EntityForm from "@/components/entities/EntityForm";
import EntitySingleColumn from "@/components/entities/EntitySingleColumn";
//Generated by GetComponentImport - GetComponentImport
import PropertyForm from "@/components/properties/PropertyForm";
import PropertySingleColumn from "@/components/properties/PropertySingleColumn";
//Generated by GetComponentImport - GetComponentImport
import PropertyStatusForm from "@/components/property-status/PropertyStatusForm";
import PropertyStatusSingleColumn from "@/components/property-status/PropertyStatusSingleColumn";

export const getModelSingleColumns = () => {
  return {
    //Generated by GetAllModelSingleColumn
//Generated by GetModelSingleColumn - GetModelSingleColumn
EntityCategory: EntityCategorySingleColumn,
//Generated by GetModelSingleColumn - GetModelSingleColumn
ContactCategory: ContactCategorySingleColumn,
//Generated by GetModelSingleColumn - GetModelSingleColumn
BuyerStatus: BuyerStatusSingleColumn,
//Generated by GetModelSingleColumn - GetModelSingleColumn
Entity: EntitySingleColumn,
//Generated by GetModelSingleColumn - GetModelSingleColumn
Property: PropertySingleColumn,
//Generated by GetModelSingleColumn - GetModelSingleColumn
PropertyStatus: PropertyStatusSingleColumn,
  };
};

export const getModelForms = () => {
  return {
    //Generated by GetAllModelForm
//Generated by GetModelForm - GetModelForm
EntityCategory: EntityCategoryForm,
//Generated by GetModelForm - GetModelForm
ContactCategory: ContactCategoryForm,
//Generated by GetModelForm - GetModelForm
BuyerStatus: BuyerStatusForm,
//Generated by GetModelForm - GetModelForm
Entity: EntityForm,
//Generated by GetModelForm - GetModelForm
Property: PropertyForm,
//Generated by GetModelForm - GetModelForm
PropertyStatus: PropertyStatusForm,
  };
};
