//Generated by WriteToModelform_tsxUsingModelconfig - ModelForm.tsx using modelConfig
"use client";
import {
  BuyerStatusFormFormikInitialValues,
  BuyerStatusModel,
  BuyerStatusSearchParams,
} from "@/interfaces/BuyerStatusInterfaces";
import { Form, Formik, FormikHelpers, FormikProps } from "formik";
import React, { MouseEventHandler, useEffect, useRef, useState } from "react";
import { BasicModel } from "@/interfaces/GeneralInterfaces";
import { useListURLStore, useURL } from "@/hooks/useURL";
import { Button } from "@/components/ui/Button";
import Breadcrumb from "@/components/ui/Breadcrumb";
import { toast } from "@/hooks/use-toast";
import { Trash } from "lucide-react";
import { findModelPrimaryKeyField } from "@/utils/utilities";
import { BuyerStatusConfig } from "@/utils/config/BuyerStatusConfig";
import { mapOriginalSimpleModels } from "@/lib/mapOriginalSimpleModels";
import { createRequiredModelLists } from "@/lib/createRequiredModelLists";
import { useModelQuery } from "@/hooks/useModelQuery";
import { generateDeletedAndNewSimpleecords } from "@/lib/generateDeletedAndNewSimpleecords";
import { FormikFormControlGenerator } from "@/components/FormikFormControlGenerator";
import { ModelSchema } from "@/schema/ModelSchema";
import { getInitialValues } from "@/lib/getInitialValues";
import { createClientPayload } from "@/lib/createClientPayload";
import { updateFormFieldsBasedOnRelationships } from "@/lib/updateFormFieldsBasedOnRelationships";
import { updateSimpleModelsBasedOnRelationships } from "@/lib/updateSimpleModelsBasedOnRelationships";
import FormikSubformGenerator from "@/components/FormikSubformGenerator";
import { getPrevURL } from "@/lib/getPrevURL";
import { ModelDeleteDialog } from "@/components/ModelDeleteDialog";
import ModelDropzonesForRelationships from "@/components/ModelDropzonesForRelationships";
import { generateGridTemplateAreas } from "@/lib/generateGridTemplateAreas";
import { cn } from "@/lib/utils";
import { getFirstAndLastFieldInForm } from "@/lib/getFirstAndLastFieldInForm";
import useScreenSize from "@/hooks/useScreenSize";
import { removeRequiredListFromLocalStorage } from "@/lib/removeRequiredListFromLocalStorage";
import { generateDeletedChildRecords } from "@/lib/generateDeletedChildRecords";
import { FormikFormFieldGroupGenerator } from "@/components/FormikFormFieldGroupGenerator";
import FormikTabGroup from "@/components/formik/FormikTabGroup/FormikTabGroup";


interface ModelFormProps {
  onSuccess: () => void;
}

interface BuyerStatusFormProps {
  data: BuyerStatusModel | null;
  id: string;
  modalFormProps?: ModelFormProps;
  hiddenField?: string;
  defaultValues?: Record<string, unknown>;
  onSubmit?: (
    values: BuyerStatusFormFormikInitialValues,
    formik: FormikHelpers<BuyerStatusFormFormikInitialValues>
  ) => void;
}

const modelConfig = BuyerStatusConfig;
const primaryKeyField = findModelPrimaryKeyField(modelConfig).fieldName;
const slugField = modelConfig.slugField || primaryKeyField;

const BuyerStatusForm: React.FC<BuyerStatusFormProps> = (prop) => {
  const { id, modalFormProps, hiddenField, onSubmit, defaultValues } = prop;
  const { router, query, pathname } = useURL<BuyerStatusSearchParams>();

  //Local states
  const [mounted, setMounted] = useState(false);
  const [recordName, setRecordName] = useState(
    prop.data
      ? modelConfig.slugField
        ? (prop.data[modelConfig.slugField as keyof typeof prop.data] as string)
        : prop.data.id.toString()
      : "New " + modelConfig.verboseModelName
  );
  const [isUpdating, setIsUpdating] = useState(false);
  const [hasUpdate, setHasUpdate] = useState(false);
  const [recordsToDelete, setRecordsToDelete] = useState<string[]>([]);
  //{ BuyerStatusTags: [] } ->
  const [originalSimpleModels, setOriginalSimpleModels] = useState(
    mapOriginalSimpleModels(
      prop as unknown as Record<string, unknown>,
      modelConfig
    )
  );

  const ref = useRef<any>(null);

  const { listURL } = useListURLStore((state) => ({
    listURL: state.listURL,
  }));

  //Derive prev URL from the listURL
  const prevURL = getPrevURL(listURL, modelConfig, pathname);

  const requiredList: Record<string, BasicModel[]> =
    createRequiredModelLists(modelConfig);

  //Generated by GetAllRelatedListFromRightRelatedModel

  const { modelMutation, modelQuery } = useModelQuery(modelConfig, id, {
    enabled: mounted && id !== "new",
    initialData: prop.data,
  });

  const buyerStatus =
    prop.data || (modelQuery.data as BuyerStatusFormFormikInitialValues);

  const isLarge = useScreenSize("lg");
  const initialValues =
    getInitialValues<BuyerStatusFormFormikInitialValues>(
      modelConfig,
      //@ts-ignore
      buyerStatus,
      {
        requiredList,
        skipEmptyRow: isLarge,
        defaultValues: hiddenField ? { [hiddenField]: 0 } : undefined,
      }
    );

  if (buyerStatus) {
    //@ts-ignore
    initialValues["index"] = buyerStatus["index"];
  }

  const handleFocus = () => {
    ref && ref.current && ref.current.focus();
  };

  const handleHasUdpate = () => {
    setHasUpdate(true);
  };

  const handleFormikSubmit = (
    values: BuyerStatusFormFormikInitialValues,
    formik: FormikHelpers<BuyerStatusFormFormikInitialValues>
  ) => {
    //Additional Validation goes here
    /*
    if (hasUpdate) {
      const additionalValidationResponse = validateBuyerStatus(values);

      if (additionalValidationResponse.status === "error") {
        toast({
          description: additionalValidationResponse.message,
          variant: "destructive",
          duration: 2000,
        });
        setIsUpdating(false);
        return;
      }
    }
    */
    //This property of the form is used to override the default form submission
    if (onSubmit) {
      onSubmit(values, formik);
      return;
    }

    //@ts-ignore
    const addNew: boolean = values.addNew;
    setIsUpdating(true);

    const goToNewRecord = () => {
      formik.setValues(
        getInitialValues<BuyerStatusFormFormikInitialValues>(
          modelConfig,
          undefined,
          { requiredList }
        )
      );
      if (!modalFormProps) {
        window.history.pushState(
          {},
          "",
          `${window.location.origin}/${modelConfig.modelPath}/new`
        );
      }

      setRecordName(`New ${modelConfig.verboseModelName}`);

      const [firstFieldInForm, _] = getFirstAndLastFieldInForm(
        modelConfig.fields
      );
      (document.querySelector(`#${firstFieldInForm}`) as HTMLElement)!.focus();
    };

    //e.g. { deletedBuyerStatusTags: [], newTags: []}
    const deletedAndNewSimpleRecords = generateDeletedAndNewSimpleecords(
      modelConfig,
      originalSimpleModels,
      //@ts-ignore
      values
    );

    //e.g. { deleteBuyerStatus: [] }
    const deletedChildRecords = generateDeletedChildRecords(
      modelConfig,
      buyerStatus,
      values
    );

    if (hasUpdate) {
      const payload = createClientPayload(
        //@ts-ignore
        values,
        modelConfig,
        deletedAndNewSimpleRecords,
        deletedChildRecords
      );
      modelMutation
        //@ts-ignore
        .mutateAsync(payload)
        .then((data) => {
          /* 
          {status: 'success',id: 1,modelsToRequery: [ 'SubAccountTitles' ],newRecords: {},SubAccountTitles: []
          } 
          */
          removeRequiredListFromLocalStorage(
            modelConfig.modelPath,
            data.modelsToRequery as string[]
          );
          if (addNew) {
            goToNewRecord();
          } else {
            //if there's a primary key field returned from the api then replace the formik value with it
            if (data[primaryKeyField]) {
              formik.setFieldValue(primaryKeyField, data[primaryKeyField]);

              if (!modalFormProps) {
                window.history.pushState(
                  {},
                  "",
                  `${window.location.origin}/${modelConfig.modelPath}/${data[primaryKeyField]}`
                );
              }
            }

            //This will replace the breadcrum record name
            setRecordName(
              data[slugField]
                ? (data[slugField] as string)
                : (values[slugField as keyof typeof values] as string)
            );

            updateFormFieldsBasedOnRelationships(
              modelConfig,
              formik,
              //@ts-ignore
              values,
              data
            );

            updateSimpleModelsBasedOnRelationships(
              modelConfig,
              originalSimpleModels,
              setOriginalSimpleModels,
              data,
              deletedAndNewSimpleRecords
            );

            if (!modalFormProps) {
              router.replace(prevURL);
            } else {
              modalFormProps.onSuccess();
            }
          }

          toast({
            description: `${modelConfig.verboseModelName} list updated successfully`,
            variant: "success",
            duration: 2000,
          });

          setIsUpdating(false);
        })
        .catch((err) => {
          console.log(err);
          setIsUpdating(false);
        });
    } else {
      if (addNew) {
        goToNewRecord();
      }
      setIsUpdating(false);
    }
  };

  const renderFormik = (
    formik: FormikProps<BuyerStatusFormFormikInitialValues>
  ) => {
    const handleSubmitClick: MouseEventHandler = (e) => {
      e.preventDefault();
      formik.submitForm();
    };

    return (
      <Form
        className="flex flex-col flex-1 h-full gap-4"
        autoComplete="off"
      >
        <div className="flex flex-col flex-1 h-full gap-8 xl:flex-row">
          <div className="flex flex-col flex-1 gap-4">
            <div
              /* className="grid xl:grid-cols-[repeat(9,1fr)_auto_auto_auto] gap-4" */
              className="grid grid-cols-12 gap-4"
              style={{
                gridTemplateAreas: generateGridTemplateAreas(modelConfig),
              }}
              /*
              Overriding rows example
              style={{
                gridTemplateAreas: generateGridTemplateAreas(
                  modelConfig,
                  isLarge
                    ? {
                        fieldsToExclude: ["notes"],
                        rowsToDelete: [0, 0],
                        rowsToAdd: {
                          0: fillArray(12, "entity_name"),
                          1: fillArray(12, "entity_category_id"),
                          2: fillArray(12, "contact_category_id"),
                          3: fillArray(12, "association"),
                          4: fillArray(12, "buyer_status_id"),
                          5: fillArray(12, "customer_type"),
                          6: fillArray(12, "to_be_contacted_date"),
                          "-1": fillArray(12, "notes"),
                        },
                      }
                    : {
                        fieldsToExclude: ["notes"],
                        rowsToAdd: {
                          "-1": fillArray(12, "notes"),
                        },
                      }
                ),
              */
            >
              {/*
                  Use this to add an AfterUpdate event for thoe form
                 <BuyerStatusAfterUpdate
                   modelConfig={modelConfig}
                requiredList={requiredList}
              />
              */}
              <FormikFormControlGenerator
                modelConfig={modelConfig}
                options={{
                  requiredList,
                  setHasUpdate: handleHasUdpate,
                  onChange: {
                    /*
                    Adds onChange event for a specific control(s) in the form
                    finishDateTime: (newValue) => {
                      if (newValue) {
                        formik.setFieldValue("isFinished", true);
                      } else {
                        formik.setFieldValue("isFinished", false);
                      }
                    },
                    isFinished: (newValue) => {
                      if (newValue) {
                        formik.setFieldValue(
                          "finishDateTime",
                          toValidDateTime(new Date())
                        );
                      } else {
                        formik.setFieldValue("finishDateTime", "");
                      }
                    },
                    */
                  },
                  hiddenField,
                }}
                //Add controls to be overriden here
                /*
                controlsToOverride={{ is_favorite: FavoriteButton }
                */
                ref={ref}
              />
              <FormikFormFieldGroupGenerator
                modelConfig={modelConfig}
                ref={ref}
                //If relayouting of the group field is needed.
                /*
                gridTemplateOptions={{
                  "Contact Information": isLarge
                    ? {
                        rowsToDelete: [1],
                        rowsToAdd: {
                          1: fillArray(12, "phone_number"),
                          2: fillArray(12, "email_address"),
                          3: fillArray(12, "website"),
                        },
                      }
                    : undefined,
                }}
                */
              />
              <FormikSubformGenerator
                modelConfig={modelConfig}
                formik={formik}
                handleHasUdpate={handleHasUdpate}
                /* 
                option={{
                  BuyerStatus: {
                    handleBlur: {
                      debit_amount: (newValue) => alert(newValue),
                    },
                  },
                }} 
                */
                /*
              Use to filter out the row data for pre-filtering records to be shown to the users
              filterFunction={{ TaskNote: (item) => !item.file }}
              */
              />
              <ModelDropzonesForRelationships
                formik={formik}
                handleHasUpdate={handleHasUdpate}
                modelConfig={modelConfig}
              />
            </div>
            {/* Controls inside the Tabs goes here */}
            <FormikTabGroup modelConfig={modelConfig} />
          </div>
        </div>
        <div
          className={cn(
            "flex flex-col md:flex-row gap-2 mt-auto",
            modalFormProps && "pt-8"
          )}
        >
          <Button
            type="button"
            size={"sm"}
            variant={"secondary"}
            onClick={(e) => {
              formik.setFieldValue("addNew", true);
              handleSubmitClick(e);
            }}
            isLoading={isUpdating}
          >
            Save & Add New
          </Button>
          <Button
            type="button"
            size={"sm"}
            variant={"secondary"}
            onClick={(e) => {
              formik.setFieldValue("addNew", false);
              handleSubmitClick(e);
            }}
            isLoading={isUpdating}
          >
            Save
          </Button>
          {modalFormProps ? null : (
            <Button
              type="button"
              size={"sm"}
              variant={"ghost"}
              onClick={(e) => {
                e.preventDefault();
                router.push(prevURL);
              }}
            >
              Back
            </Button>
          )}

          {(id !== "new" ||
            recordName !== "New " + modelConfig.verboseModelName) && (
            <Button
              type="button"
              size={"sm"}
              variant={"destructive"}
              onClick={(e) => {
                setRecordsToDelete([
                  //@ts-ignore
                  formik.values[primaryKeyField].toString(),
                ]);
              }}
              className={"ml-auto w-full md:w-auto"}
            >
              <Trash className="w-4 h-4 mr-2" />
              Delete
            </Button>
          )}
        </div>
      </Form>
    );
  };

  useEffect(() => {
    setMounted(true);
    handleFocus();
  }, []);

  return mounted ? (
    <>
      {!modalFormProps ? (
        <Breadcrumb
          links={[
            { name: modelConfig.pluralizedVerboseModelName, href: prevURL },
            { name: recordName, href: "" },
          ]}
        />
      ) : null}

      <Formik
        initialValues={initialValues}
        onSubmit={handleFormikSubmit}
        validateOnChange={false}
        validateOnBlur={false}
        enableReinitialize={false}
        validationSchema={ModelSchema(modelConfig)}
      >
        {renderFormik}
      </Formik>
      <ModelDeleteDialog
        modelConfig={modelConfig}
        recordsToDelete={recordsToDelete}
        setRecordsToDelete={setRecordsToDelete}
        onSuccess={() => {
          toast({
            description:
              modelConfig.verboseModelName + " successfully deleted.",
            variant: "success",
            duration: 4000,
          });
          router.replace(prevURL);
        }}
      />
    </>
  ) : null;
};

export default BuyerStatusForm;
