//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import BuyerStatusFilterForm from "@/components/buyer-status/BuyerStatusFilterForm";
import BuyerStatusTable from "@/components/buyer-status/BuyerStatusTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { BuyerStatusModel } from "@/interfaces/BuyerStatusInterfaces";
import React from "react";

const BuyerStatusStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<BuyerStatusModel>(modelConfig);
  return (
    <>
      <h1 className="text-2xl font-bold">
        {modelConfig.pluralizedVerboseModelName}
      </h1>
      <div className="flex">
        <BuyerStatusFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <BuyerStatusTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default BuyerStatusStateHolder;
