//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { BuyerStatusModel } from "@/interfaces/BuyerStatusInterfaces";
import { BuyerStatusConfig } from "@/utils/config/BuyerStatusConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = BuyerStatusConfig;

const BuyerStatusSingleColumn = <T,>({ 
  cell,
relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const buyerStatus = cell.row.original as BuyerStatusModel;
  return (
    <div className="flex flex-col gap-1">
      {generateModelSingleColumnFromFields(modelConfig, buyerStatus, relationshipConfig)}
    </div>
  );
};

export default BuyerStatusSingleColumn;
