//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { BuyerStatusModel } from "@/interfaces/BuyerStatusInterfaces";
import { BuyerStatusConfig } from "@/utils/config/BuyerStatusConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = BuyerStatusConfig;

const BuyerStatusSingleColumn = <T,>({ 
  cell,
relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const buyerStatus = cell.row.original as BuyerStatusModel;

  /*
  //To fetch a certain related field when using a subform since direct object won't be accessible
  const subAccountTitle = getListItemFromLocalStorage(
    "sub-account-titles",
    "id",
    journalEntryItem,
    "sub_account_title_id"
  );
  */

  return (
    <div className="flex flex-col gap-1">
      {generateModelSingleColumnFromFields(modelConfig, buyerStatus, relationshipConfig)}
    </div>
  );
};

export default BuyerStatusSingleColumn;
