//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PageSession from "@/components/PageSession";
import { ContactCategoryConfig } from "@/utils/config/ContactCategoryConfig";
import ContactCategoryStateHolder from "@/components/contact-categories/ContactCategoryStateHolder";

const config = ContactCategoryConfig;

export const metadata = {
  title: config.pluralizedVerboseModelName,
};

const ContactCategories: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full mx-auto text-sm 2xl:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 pl-4 mx-auto rounded-sm">
          <ContactCategoryStateHolder modelConfig={config} />
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default ContactCategories;
