//Generated by WriteToGetmodelcolumnstobeoverriden_tsx - getModelColumnsToBeOverriden.tsx
import { Badge } from "@/components/ui/Badge";
import { DataTableColumnHeader } from "@/components/ui/DataTable/DataTableColumnHeader";
import { EntityModel } from "@/interfaces/EntityInterfaces";
import { UnknownObject } from "@/interfaces/GeneralInterfaces";
import { ColumnsToBeOverriden } from "@/lib/table-utils";
import { HeaderContext, CellContext } from "@tanstack/react-table";
import { BookUser } from "lucide-react";

export const getEntityColumnsToBeOverriden = <TData, TValue>() => {
  return {
    address: {
      header: (header: HeaderContext<TData, TValue>) => (
        <DataTableColumnHeader
          column={header.column}
          title={"Details"}
        />
      ),
      cell: (cell: CellContext<TData, TValue>) => {
        const row = cell.row.original as EntityModel;
        return (
          <div className="flex gap-2">
            <BookUser className="h-3 w-3 mt-1 shrink-0" />
            <div>{row.address}</div>
          </div>
        );
      },
    },
    //Generated column (meaning this column doesn't exist from the original field)
    /* debitTotal: {
      header: (header: HeaderContext<TData, TValue>) => (
        <DataTableColumnHeader
          column={header.column}
          title={"Debit"}
        />
      ),
      cell: (cell: CellContext<TData, TValue>) => {
        const row = cell.row.original as JournalEntryModel;
        return (
          <div>
            {row.JournalEntryItems.reduce(
              (prev, cur) => (prev + cur.debit_amount) as unknown as number,
              0
            ).toFixed(2)}
          </div>
        );
      },
      footer: (footer: HeaderContext<TData, TValue>) => null,
      meta: {
        alignment: "right",
      },
      enableSorting: false,
    }, */
  } as ColumnsToBeOverriden<TData, TValue>;
};
