//Generated by WriteToGetmodelcolumnstobeoverriden_tsx - getModelColumnsToBeOverriden.tsx
import { Badge } from "@/components/ui/Badge";
import { DataTableColumnHeader } from "@/components/ui/DataTable/DataTableColumnHeader";
import { GenericTooltip } from "@/components/ui/Tooltip";
import { EntityModel } from "@/interfaces/EntityInterfaces";
import { UnknownObject } from "@/interfaces/GeneralInterfaces";
import { ColumnsToBeOverriden } from "@/lib/table-utils";
import { HeaderContext, CellContext } from "@tanstack/react-table";
import { BookUser, Globe, Mail, Phone } from "lucide-react";

const renderIconAndCaption = (
  Icon: React.ComponentType<any>,
  caption: string | null
) => {
  if (!caption) return null;
  return (
    <div className="flex gap-1">
      <Icon className="w-3 h-3 mt-1 shrink-0" />
      <div>{caption}</div>
    </div>
  );
};

export const getEntityColumnsToBeOverriden = <TData, TValue>() => {
  return {
    address: {
      header: (header: HeaderContext<TData, TValue>) => (
        <DataTableColumnHeader
          column={header.column}
          title={"Details"}
        />
      ),
      cell: (cell: CellContext<TData, TValue>) => {
        const row = cell.row.original as EntityModel;
        return (
          <>
            {renderIconAndCaption(BookUser, row.address)}
            {renderIconAndCaption(Phone, row.phone_number)}
            {renderIconAndCaption(Mail, row.email_address)}
            {renderIconAndCaption(Globe, row.website)}
          </>
        );
      },
    },
    entity_category_id: {
      cell: (cell: CellContext<TData, TValue>) => {
        const row = cell.row.original as EntityModel;
        return (
          <div className="flex flex-col gap-1">
            {row.EntityCategory.name}{" "}
            {row.BuyerStatus?.name && (
              <GenericTooltip
                Content="Buyer Status"
                Trigger={
                  <span className="px-2 text-xs rounded-lg w-fit bg-muted">
                    {row.BuyerStatus.name}
                  </span>
                }
              />
            )}
          </div>
        );
      },
    },
    //Generated column (meaning this column doesn't exist from the original field)
    /* debitTotal: {
      header: (header: HeaderContext<TData, TValue>) => (
        <DataTableColumnHeader
          column={header.column}
          title={"Debit"}
        />
      ),
      cell: (cell: CellContext<TData, TValue>) => {
        const row = cell.row.original as JournalEntryModel;
        return (
          <div>
            {row.JournalEntryItems.reduce(
              (prev, cur) => (prev + cur.debit_amount) as unknown as number,
              0
            ).toFixed(2)}
          </div>
        );
      },
      footer: (footer: HeaderContext<TData, TValue>) => null,
      meta: {
        alignment: "right",
      },
      enableSorting: false,
    }, */
  } as ColumnsToBeOverriden<TData, TValue>;
};
