//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import ContactCategoryFilterForm from "@/components/contact-categories/ContactCategoryFilterForm";
import ContactCategoryTable from "@/components/contact-categories/ContactCategoryTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { ContactCategoryModel } from "@/interfaces/ContactCategoryInterfaces";
import React from "react";

const ContactCategoryStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<ContactCategoryModel>(modelConfig);
  return (
    <>
      <div className="flex">
        <ContactCategoryFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <ContactCategoryTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default ContactCategoryStateHolder;
