//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PageSession from "@/components/PageSession";
import { PropertyConfig } from "@/utils/config/PropertyConfig";
import PropertyStateHolder from "@/components/properties/PropertyStateHolder";

const config = PropertyConfig;

export const metadata = {
  title: config.pluralizedVerboseModelName,
};

const Properties: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full mx-auto text-sm 2xl:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 pl-4 mx-auto rounded-sm">
          <PropertyStateHolder modelConfig={config} />
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default Properties;
