//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { PropertyStatusModel } from "@/interfaces/PropertyStatusInterfaces";
import { PropertyStatusConfig } from "@/utils/config/PropertyStatusConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = PropertyStatusConfig;

const PropertyStatusSingleColumn = <T,>({
  cell,
  relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const propertyStatus = cell.row.original as PropertyStatusModel;

  /*
  //To fetch a certain related field when using a subform since direct object won't be accessible
  const subAccountTitle = getListItemFromLocalStorage(
    "sub-account-titles",
    "id",
    journalEntryItem,
    "sub_account_title_id"
  );
  */

  return (
    <div className="flex flex-col gap-4 py-4">
      {generateModelSingleColumnFromFields(
        modelConfig,
        propertyStatus,
        relationshipConfig
        //Fields to be overriden use the fieldName
        /* {
          is_favorite: (
            <Button
              variant={"ghost"}
              className={cn("w-5 h-5 p-0 rounded-full ", {
                "text-green-600": propertyStatus.is_favorite,
                "hover:text-green-600": !propertyStatus.is_favorite,
              })}
            >
              <SiFoodpanda className="w-5 h-5" />
            </Button>
          ),
          street_address: (
            <h1 className="font-bold tracking-widest">
              {propertyStatus.street_address}
            </h1>
          ),
          suburb: (
            <div className="text-xs">
              {propertyStatus.suburb} ({propertyStatus.postcode})
            </div>
          ),
          state: (
            <div className="px-2 text-xs rounded-full bg-accent">
              {propertyStatus.state}
            </div>
          ),
          bed: (
            <div className="flex items-center gap-2">
              <Bed className="w-5 h-5" />
              {propertyStatus.bed}
            </div>
          ),
          bath: (
            <div className="flex items-center gap-2">
              <Bath className="w-5 h-5" />
              {propertyStatus.bath}
            </div>
          ),
          car: (
            <div className="flex items-center gap-2">
              <Car className="w-5 h-5" />
              {propertyStatus.car}
            </div>
          ),
        } */
      )}
    </div>
  );
};

export default PropertyStatusSingleColumn;
