//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { PropertyStatusModel } from "@/interfaces/PropertyStatusInterfaces";
import { PropertyStatusConfig } from "@/utils/config/PropertyStatusConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = PropertyStatusConfig;

const PropertyStatusSingleColumn = <T,>({ 
  cell,
relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const propertyStatus = cell.row.original as PropertyStatusModel;

  /*
  //To fetch a certain related field when using a subform since direct object won't be accessible
  const subAccountTitle = getListItemFromLocalStorage(
    "sub-account-titles",
    "id",
    journalEntryItem,
    "sub_account_title_id"
  );
  */

  return (
    <div className="flex flex-col gap-1">
      {generateModelSingleColumnFromFields(modelConfig, propertyStatus, relationshipConfig)}
    </div>
  );
};

export default PropertyStatusSingleColumn;
