//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import PropertyStatusFilterForm from "@/components/property-status/PropertyStatusFilterForm";
import PropertyStatusTable from "@/components/property-status/PropertyStatusTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { PropertyStatusModel } from "@/interfaces/PropertyStatusInterfaces";
import React from "react";

const PropertyStatusStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<PropertyStatusModel>(modelConfig);
  return (
    <>
      <h1 className="text-2xl font-bold">
        {modelConfig.pluralizedVerboseModelName}
      </h1>
      <div className="flex">
        <PropertyStatusFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <PropertyStatusTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default PropertyStatusStateHolder;
