//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import PropertyFilterForm from "@/components/properties/PropertyFilterForm";
import PropertyTable from "@/components/properties/PropertyTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { PropertyModel } from "@/interfaces/PropertyInterfaces";
import React from "react";

const PropertyStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<PropertyModel>(modelConfig);
  return (
    <>
      <h1 className="text-2xl font-bold">
        {modelConfig.pluralizedVerboseModelName}
      </h1>
      <div className="flex">
        <PropertyFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <PropertyTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default PropertyStateHolder;
