//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { PropertyModel } from "@/interfaces/PropertyInterfaces";
import { PropertyConfig } from "@/utils/config/PropertyConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = PropertyConfig;

const PropertySingleColumn = <T,>({ 
  cell,
relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const property = cell.row.original as PropertyModel;

  /*
  //To fetch a certain related field when using a subform since direct object won't be accessible
  const subAccountTitle = getListItemFromLocalStorage(
    "sub-account-titles",
    "id",
    journalEntryItem,
    "sub_account_title_id"
  );
  */

  return (
    <div className="flex flex-col gap-1">
      {generateModelSingleColumnFromFields(modelConfig, property, relationshipConfig)}
    </div>
  );
};

export default PropertySingleColumn;
