//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PageSession from "@/components/PageSession";
import { PropertyStatusConfig } from "@/utils/config/PropertyStatusConfig";
import PropertyStatusStateHolder from "@/components/property-status/PropertyStatusStateHolder";

const config = PropertyStatusConfig;

export const metadata = {
  title: config.pluralizedVerboseModelName,
};

const PropertyStatus: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full mx-auto text-sm 2xl:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 pl-4 mx-auto rounded-sm">
          <PropertyStatusStateHolder modelConfig={config} />
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default PropertyStatus;
