//Generated by WriteToModelsPage - Model Page Sidebar
import React from "react";
import PageSession from "@/components/PageSession";
import { BuyerStatusConfig } from "@/utils/config/BuyerStatusConfig";
import BuyerStatusStateHolder from "@/components/buyer-status/BuyerStatusStateHolder";

const config = BuyerStatusConfig;

export const metadata = {
  title: config.pluralizedVerboseModelName,
};

const BuyerStatus: React.FC = () => {
  return (
    <>
      <div className="flex flex-col flex-1 w-full mx-auto text-sm 2xl:px-0 main-height-less-footer">
        <div className="flex flex-col flex-1 w-full gap-4 pl-4 mx-auto rounded-sm">
          <BuyerStatusStateHolder modelConfig={config} />
        </div>
      </div>
      <PageSession />
    </>
  );
};

export default BuyerStatus;
