//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { EntityModel } from "@/interfaces/EntityInterfaces";
import { EntityConfig } from "@/utils/config/EntityConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = EntityConfig;

const EntitySingleColumn = <T,>({ 
  cell,
relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const entity = cell.row.original as EntityModel;
  return (
    <div className="flex flex-col gap-1">
      {generateModelSingleColumnFromFields(modelConfig, entity, relationshipConfig)}
    </div>
  );
};

export default EntitySingleColumn;
