//Generated by WriteToModelstateholder_tsx - ModelStateHolder.tsx
"use client";
import EntityFilterForm from "@/components/entities/EntityFilterForm";
import EntityTable from "@/components/entities/EntityTable";
import { useTableProps } from "@/hooks/useTableProps";
import { ModelConfig } from "@/interfaces/ModelConfig";
import { EntityModel } from "@/interfaces/EntityInterfaces";
import React from "react";

const EntityStateHolder = ({ modelConfig }: { modelConfig: ModelConfig }) => {
  const tableStates = useTableProps<EntityModel>(modelConfig);
  return (
    <>
      <h1 className="text-2xl font-bold">
        {modelConfig.pluralizedVerboseModelName}
      </h1>
      <div className="flex">
        <EntityFilterForm tableStates={tableStates} />
      </div>
      <div className="flex flex-col flex-1 ">
        <EntityTable tableStates={tableStates} />
      </div>
    </>
  );
};

export default EntityStateHolder;
