//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { EntityModel } from "@/interfaces/EntityInterfaces";
import { EntityConfig } from "@/utils/config/EntityConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = EntityConfig;

const EntitySingleColumn = <T,>({ 
  cell,
relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const entity = cell.row.original as EntityModel;

  /*
  //To fetch a certain related field when using a subform since direct object won't be accessible
  const subAccountTitle = getListItemFromLocalStorage(
    "sub-account-titles",
    "id",
    journalEntryItem,
    "sub_account_title_id"
  );
  */

  return (
    <div className="flex flex-col gap-1">
      {generateModelSingleColumnFromFields(modelConfig, entity, relationshipConfig)}
    </div>
  );
};

export default EntitySingleColumn;
