//Generated by WriteToLucideicons_tsx - LucideIcons.tsx
import {
  BarChart2,
  //Generated by GetAllLucideIcons
  //Generated by GetLucideIcon - GetLucideIcon
  User2,
} from "lucide-react";

export const LucideIcons = {
  BarChart2,
  //Generated by GetAllLucideIconItems
  //Generated by GetLucideIconItem - GetLucideIcon
  User2,
};
