//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import { EntityFormikInitialValues, EntityFormikShape,EntityModel,EntityUpdatePayload } from "@/interfaces/EntityInterfaces";

import { ListQuery } from "./interface";

export interface BuyerStatusModel {
  //Generated by GetAllModelFieldTypeBySeqModel
name: string;//Generated by GetModelFieldType
id: number | string;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
Entities: EntityModel[];//Generated by GetChildModelInterface - ChildModelInterface
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface BuyerStatusFormikShape extends Omit<BuyerStatusModel, "slug" | "createdAt" | "updatedAt" 
| "Entities"//Generated by GetRelatedPluralizedModelName - RelatedPluralizedModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface BuyerStatusFormikInitialValues {
  BuyerStatus: BuyerStatusFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface BuyerStatusFormFormikInitialValues
  extends Omit<BuyerStatusFormikShape, "touched" | "index"> ,EntityFormikInitialValues{
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface BuyerStatusUpdatePayload extends Partial<EntityUpdatePayload> {
  BuyerStatus: Omit<BuyerStatusFormikShape, "touched">[];
  
}

export interface BuyerStatusDeletePayload {
  deletedBuyerStatus: string[] | number[];
}

export interface BuyerStatusSelectedPayload {
  selectedBuyerStatus: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface BuyerStatusFormUpdatePayload
  extends Omit<BuyerStatusFormikShape, "touched" | "index" 
> 
//Generated by GetAllRelatedModelUpdatePayload
,//Generated by GetModelUpdatePayload - ModelUpdatePayload
EntityUpdatePayload 
{
  
}

export interface BuyerStatusFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface BuyerStatusSearchParams
  extends ListQuery,
    Omit<BuyerStatusFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetBuyerStatusResponse {
  count: number;
  rows: BuyerStatusModel[];
  cursor: string;
}
