//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import { EntityFormikInitialValues, EntityFormikShape,EntityModel,EntityUpdatePayload } from "@/interfaces/EntityInterfaces";

import { ListQuery } from "./interface";

export interface ContactCategoryModel {
  //Generated by GetAllModelFieldTypeBySeqModel
name: string;//Generated by GetModelFieldType
id: number | string;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
Entities: EntityModel[];//Generated by GetChildModelInterface - ChildModelInterface
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface ContactCategoryFormikShape extends Omit<ContactCategoryModel, "slug" | "createdAt" | "updatedAt" 
| "Entities"//Generated by GetRelatedPluralizedModelName - RelatedPluralizedModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface ContactCategoryFormikInitialValues {
  ContactCategories: ContactCategoryFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface ContactCategoryFormFormikInitialValues
  extends Omit<ContactCategoryFormikShape, "touched" | "index"> ,EntityFormikInitialValues{
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface ContactCategoryUpdatePayload extends Partial<EntityUpdatePayload> {
  ContactCategories: Omit<ContactCategoryFormikShape, "touched">[];
  
}

export interface ContactCategoryDeletePayload {
  deletedContactCategories: string[] | number[];
}

export interface ContactCategorySelectedPayload {
  selectedContactCategories: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface ContactCategoryFormUpdatePayload
  extends Omit<ContactCategoryFormikShape, "touched" | "index" 
> 
//Generated by GetAllRelatedModelUpdatePayload
,//Generated by GetModelUpdatePayload - ModelUpdatePayload
EntityUpdatePayload 
{
  
}

export interface ContactCategoryFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface ContactCategorySearchParams
  extends ListQuery,
    Omit<ContactCategoryFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetContactCategoriesResponse {
  count: number;
  rows: ContactCategoryModel[];
  cursor: string;
}
