//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import { EntityFormikInitialValues, EntityFormikShape,EntityModel,EntityUpdatePayload } from "@/interfaces/EntityInterfaces";

import { ListQuery } from "./interface";

export interface EntityCategoryModel {
  //Generated by GetAllModelFieldTypeBySeqModel
name: string;//Generated by GetModelFieldType
id: number | string;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
Entities: EntityModel[];//Generated by GetChildModelInterface - ChildModelInterface
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface EntityCategoryFormikShape extends Omit<EntityCategoryModel, "slug" | "createdAt" | "updatedAt" 
| "Entities"//Generated by GetRelatedPluralizedModelName - RelatedPluralizedModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface EntityCategoryFormikInitialValues {
  EntityCategories: EntityCategoryFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface EntityCategoryFormFormikInitialValues
  extends Omit<EntityCategoryFormikShape, "touched" | "index"> ,EntityFormikInitialValues{
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface EntityCategoryUpdatePayload extends Partial<EntityUpdatePayload> {
  EntityCategories: Omit<EntityCategoryFormikShape, "touched">[];
  
}

export interface EntityCategoryDeletePayload {
  deletedEntityCategories: string[] | number[];
}

export interface EntityCategorySelectedPayload {
  selectedEntityCategories: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface EntityCategoryFormUpdatePayload
  extends Omit<EntityCategoryFormikShape, "touched" | "index" 
> 
//Generated by GetAllRelatedModelUpdatePayload
,//Generated by GetModelUpdatePayload - ModelUpdatePayload
EntityUpdatePayload 
{
  
}

export interface EntityCategoryFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface EntityCategorySearchParams
  extends ListQuery,
    Omit<EntityCategoryFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetEntityCategoriesResponse {
  count: number;
  rows: EntityCategoryModel[];
  cursor: string;
}
