//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

//Generated by GetAllRelatedRightModelImport
import { ContactCategoryModel } from "@/interfaces/ContactCategoryInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { EntityCategoryModel } from "@/interfaces/EntityCategoryInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { BuyerStatusModel } from "@/interfaces/BuyerStatusInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface EntityModel {
  //Generated by GetAllModelFieldTypeBySeqModel
association: string | null;//Generated by GetModelFieldType
last_viewed_property: number | string | null;//Generated by GetModelFieldType
buyer_status_id: number | string | null;//Generated by GetModelFieldType
website: string | null;//Generated by GetModelFieldType
is_seller: boolean;//Generated by GetModelFieldType
customer_type: string | null;//Generated by GetModelFieldType
to_be_contacted: boolean;//Generated by GetModelFieldType
to_be_contacted_date: string | null;//Generated by GetModelFieldType
id: number | string;//Generated by GetModelFieldType
contact_category_id: number | string | null;//Generated by GetModelFieldType
entity_category_id: number | string;//Generated by GetModelFieldType
entity_name: string;//Generated by GetModelFieldType
address: string | null;//Generated by GetModelFieldType
phone_number: string | null;//Generated by GetModelFieldType
email_address: string | null;//Generated by GetModelFieldType
notes: string | null;//Generated by GetModelFieldType
createdAt: string;
updatedAt: string;
  
  
  //Generated by GetAllRelatedRightModelInterface
ContactCategory: ContactCategoryModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
EntityCategory: EntityCategoryModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
BuyerStatus: BuyerStatusModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface EntityFormikShape extends Omit<EntityModel, "slug" | "createdAt" | "updatedAt" 
| "ContactCategory"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "EntityCategory"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "BuyerStatus"//Generated by GetRelatedRightModelName - GetRelatedRightModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface EntityFormikInitialValues {
  Entities: EntityFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface EntityFormFormikInitialValues
  extends Omit<EntityFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface EntityUpdatePayload  {
  Entities: Omit<EntityFormikShape, "touched">[];
  
}

export interface EntityDeletePayload {
  deletedEntities: string[] | number[];
}

export interface EntitySelectedPayload {
  selectedEntities: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface EntityFormUpdatePayload
  extends Omit<EntityFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface EntityFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
entity_category: string;//Generated by GetThisFilterInterface
contact_category: string;//Generated by GetThisFilterInterface
buyer_status: string;//Generated by GetThisFilterInterface
}

export interface EntitySearchParams
  extends ListQuery,
    Omit<EntityFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetEntitiesResponse {
  count: number;
  rows: EntityModel[];
  cursor: string;
}
