//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13
//Generated by GetAllRelatedInterfaceImportBySeqModel
//Generated by GetRelatedInterfaceImport - RelatedInterfaceImport
import { PropertyFormikInitialValues, PropertyFormikShape,PropertyModel,PropertyUpdatePayload } from "@/interfaces/PropertyInterfaces";

import { ListQuery } from "./interface";

export interface PropertyStatusModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;//Generated by GetModelFieldType
property_status_code: string;//Generated by GetModelFieldType
property_status: string | null;//Generated by GetModelFieldType
is_shown_on_favorite: boolean;//Generated by GetModelFieldType
slug: string;
createdAt: string;
updatedAt: string;
  //Generated by GetAllChildModelInterfaceBySeqModel
Properties: PropertyModel[];//Generated by GetChildModelInterface - ChildModelInterface
  
  
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface PropertyStatusFormikShape extends Omit<PropertyStatusModel, "slug" | "createdAt" | "updatedAt" 
| "Properties"//Generated by GetRelatedPluralizedModelName - RelatedPluralizedModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface PropertyStatusFormikInitialValues {
  PropertyStatus: PropertyStatusFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface PropertyStatusFormFormikInitialValues
  extends Omit<PropertyStatusFormikShape, "touched" | "index"> ,PropertyFormikInitialValues{
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface PropertyStatusUpdatePayload extends Partial<PropertyUpdatePayload> {
  PropertyStatus: Omit<PropertyStatusFormikShape, "touched">[];
  
}

export interface PropertyStatusDeletePayload {
  deletedPropertyStatus: string[] | number[];
}

export interface PropertyStatusSelectedPayload {
  selectedPropertyStatus: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface PropertyStatusFormUpdatePayload
  extends Omit<PropertyStatusFormikShape, "touched" | "index" 
> 
//Generated by GetAllRelatedModelUpdatePayload
,//Generated by GetModelUpdatePayload - ModelUpdatePayload
PropertyUpdatePayload 
{
  
}

export interface PropertyStatusFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface PropertyStatusSearchParams
  extends ListQuery,
    Omit<PropertyStatusFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetPropertyStatusResponse {
  count: number;
  rows: PropertyStatusModel[];
  cursor: string;
}
