//Generated by WriteToModelinterface_ts - ModelInterface.ts Next 13

//Generated by GetAllRelatedRightModelImport
import { PropertyStatusModel } from "@/interfaces/PropertyStatusInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { EntityModel } from "@/interfaces/EntityInterfaces";//Generated by GetRelatedRightModelImport - GetRelatedRightModelImport
import { ListQuery } from "./interface";

export interface PropertyModel {
  //Generated by GetAllModelFieldTypeBySeqModel
id: number | string;//Generated by GetModelFieldType
property_image: string | null;//Generated by GetModelFieldType
street_address: string | null;//Generated by GetModelFieldType
suburb: string | null;//Generated by GetModelFieldType
state: string | null;//Generated by GetModelFieldType
postcode: string | null;//Generated by GetModelFieldType
property_type: string | null;//Generated by GetModelFieldType
bed: number | string | null;//Generated by GetModelFieldType
bath: number | string | null;//Generated by GetModelFieldType
car: number | string | null;//Generated by GetModelFieldType
building_area: number | string | null;//Generated by GetModelFieldType
sale_price: string | null;//Generated by GetModelFieldType
sale_date: string | null;//Generated by GetModelFieldType
settlement_date: string | null;//Generated by GetModelFieldType
sale_type: string | null;//Generated by GetModelFieldType
agency: string | null;//Generated by GetModelFieldType
agent: string | null;//Generated by GetModelFieldType
improve: string | null;//Generated by GetModelFieldType
construction: string | null;//Generated by GetModelFieldType
land_use1: string | null;//Generated by GetModelFieldType
zoning: string | null;//Generated by GetModelFieldType
development_zone: string | null;//Generated by GetModelFieldType
primary_plan: string | null;//Generated by GetModelFieldType
rpd: string | null;//Generated by GetModelFieldType
valuation_no: string | null;//Generated by GetModelFieldType
valuation_type: string | null;//Generated by GetModelFieldType
valuation_amount: string | null;//Generated by GetModelFieldType
valuation_date: string | null;//Generated by GetModelFieldType
owner1name: string | null;//Generated by GetModelFieldType
owner1address: string | null;//Generated by GetModelFieldType
owner2name: string | null;//Generated by GetModelFieldType
owner2address: string | null;//Generated by GetModelFieldType
owner3name: string | null;//Generated by GetModelFieldType
owner3address: string | null;//Generated by GetModelFieldType
vendor1name: string | null;//Generated by GetModelFieldType
vendor1address: string | null;//Generated by GetModelFieldType
vendor2name: string | null;//Generated by GetModelFieldType
vendor2address: string | null;//Generated by GetModelFieldType
vendor3name: string | null;//Generated by GetModelFieldType
vendor3address: string | null;//Generated by GetModelFieldType
relationship: string | null;//Generated by GetModelFieldType
open_in_r_p_p: string | null;//Generated by GetModelFieldType
price_undisclosed: boolean;//Generated by GetModelFieldType
is_favorite: boolean;//Generated by GetModelFieldType
buyer_name: string | null;//Generated by GetModelFieldType
property_status_id: number | string | null;//Generated by GetModelFieldType
buyer_id: number | string | null;//Generated by GetModelFieldType
appraised_amount: string | null;//Generated by GetModelFieldType
exclude_from_report: boolean;//Generated by GetModelFieldType
property_alt_links: string | null;//Generated by GetModelFieldType
property_alt_link: string | null;//Generated by GetModelFieldType
combined_owner: string | null;//Generated by GetModelFieldType
formatted_t_s: string | null;//Generated by GetModelFieldType
advertisement_id: string | null;//Generated by GetModelFieldType
commission_rate: string | null;//Generated by GetModelFieldType
contract_date: string | null;//Generated by GetModelFieldType
land_size: string | null;//Generated by GetModelFieldType
createdAt: string;
updatedAt: string;
  
  
  //Generated by GetAllRelatedRightModelInterface
PropertyStatus: PropertyStatusModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
Entity: EntityModel;//Generated by GetRelatedRightModelInterface - GetRelatedRightModelInterface
}

//The keys after the updatedAt is generated by GetAllRelatedModelNameBySeqModel - RelatedModelName
export interface PropertyFormikShape extends Omit<PropertyModel, "slug" | "createdAt" | "updatedAt" 
| "PropertyStatus"//Generated by GetRelatedRightModelName - GetRelatedRightModelName
| "Entity"//Generated by GetRelatedRightModelName - GetRelatedRightModelName 
> {
  touched: boolean;
  index: number;
}

//Use for continuos list form
export interface PropertyFormikInitialValues {
  Properties: PropertyFormikShape[];
  
}

//The FormikInitialValues is generated by GetAllRelatedFormikInitialValues - ModelFormikInitialValue
export interface PropertyFormFormikInitialValues
  extends Omit<PropertyFormikShape, "touched" | "index"> {
  
}

//The extends portion is generated by GetModelUpdatePayloadExtension - GetRelatedPartialPayload
export interface PropertyUpdatePayload  {
  Properties: Omit<PropertyFormikShape, "touched">[];
  
}

export interface PropertyDeletePayload {
  deletedProperties: string[] | number[];
}

export interface PropertySelectedPayload {
  selectedProperties: string[] | number[];
}

//Use for single form (with children)
//The Related Models will be replaced by the Payload version
export interface PropertyFormUpdatePayload
  extends Omit<PropertyFormikShape, "touched" | "index" 
> 
 
{
  
}

export interface PropertyFormikFilter {
  //Generated by GetAllFilterInterfaceBySeqmodel
q: string
}

export interface PropertySearchParams
  extends ListQuery,
    Omit<PropertyFormikFilter, ""> {
  //Generated by GetAllNonStringFilterTypes

}

export interface GetPropertiesResponse {
  count: number;
  rows: PropertyModel[];
  cursor: string;
}
