//Generated by Generate_middleware_ts
import { NextRequest, NextResponse } from "next/server";
import { createServerClient, type CookieOptions } from "@supabase/ssr";
import { AppConfig } from "@/lib/app-config";
export async function middleware(request: NextRequest) {
  let response = NextResponse.next({
    request: {
      headers: request.headers,
    },
  });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return request.cookies.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value,
            ...options,
          });
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          });
          response.cookies.set({
            name,
            value,
            ...options,
          });
        },
        remove(name: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value: "",
            ...options,
          });
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          });
          response.cookies.set({
            name,
            value: "",
            ...options,
          });
        },
      },
    }
  );

  const { data, error } = await supabase.auth.getSession();

  const { session } = data;

  const url = request.nextUrl;
  const path = url.pathname;
  const modelPaths = AppConfig.models.map((model) => `/${model.modelPath}`);
  const isCurrentPathAModelPath = modelPaths.some((modelPath) =>
    path.includes(modelPath)
  );
  //const isCurrentPathIsHomePage = false;
  const isCurrentPathIsHomePage = path === "/";
  const domain = process.env.NEXT_PUBLIC_DOMAIN;
  if (!session && (isCurrentPathAModelPath || isCurrentPathIsHomePage)) {
    return NextResponse.redirect(`${domain}/login`);
  }

  if (session && isCurrentPathIsHomePage) {
    return NextResponse.redirect(`${domain}/dashboard`);
  }

  response.headers.set("Access-Control-Allow-Origin", "*");

  /* 
  //Another option allow only if the origin matches the desired origin
  if (origin){
    const originRegex = /^https:\/\/www\.mydomain\.com$/;
    if (originRegex.test(origin)) {
      // Allow only this origin
      response.headers.set("Access-Control-Allow-Origin", origin);
    } else {
      // Deny any other origin
      response.headers.set("Access-Control-Allow-Origin", "null");
    }
  }
 */
  response.headers.set(
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, DELETE, OPTIONS"
  );
  response.headers.set(
    "Access-Control-Allow-Headers",
    "Content-Type, Authorization"
  );
  response.headers.set("Access-Control-Max-Age", "86400");

  return response;
}

export const config = {
  matcher: "/(.*)",
};
