//Generated by WriteToLayout_tsx - GenerateMainLayoutSidebar
import Footer from "@/components/Footer";
import SessionButton from "@/components/header/SessionButton";
import Sidebar from "@/components/sidebar/Sidebar";
import DarkLightToggle from "@/components/header/DarkLightToggle";
import { GlobalDialog } from "@/components/GlobalDialog";
import MenuButton from "@/components/header/MenuButton";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Sidebar />
      <main className="flex flex-col flex-1 gap-4 pt-4 pl-0 pr-4">
        <div className="flex w-full gap-4 pl-4">
          <MenuButton />
          <div className="flex gap-4 ml-auto">
            <SessionButton />
            <DarkLightToggle />
          </div>
        </div>
        {children}
        <GlobalDialog />
        <Footer />
      </main>
    </>
  );
}
