//Generated by WriteToModelsinglecolumn_tsx - ModelSingleColumn.tsx
import { ModelSingleColumnProps } from "@/interfaces/GeneralInterfaces";
import { EntityCategoryModel } from "@/interfaces/EntityCategoryInterfaces";
import { EntityCategoryConfig } from "@/utils/config/EntityCategoryConfig";
import { generateModelSingleColumnFromFields } from "@/lib/generateModelSingleColumnFromFields";

const modelConfig = EntityCategoryConfig;

const EntityCategorySingleColumn = <T,>({ 
  cell,
relationshipConfig,
}: ModelSingleColumnProps<T>) => {
  const entityCategory = cell.row.original as EntityCategoryModel;
  return (
    <div className="flex flex-col gap-1">
      {generateModelSingleColumnFromFields(modelConfig, entityCategory, relationshipConfig)}
    </div>
  );
};

export default EntityCategorySingleColumn;
